#!/bin/bash

chmod +x 01_connect_ec2
chmod +x 02_root
chmod +x 03_install_wget
chmod +x 04_download_jdk19
chmod +x 05_install_jdk19
chmod +x 06_download_server
chmod +x 07_run_server_1
chmod +x 08_run_server_2
chmod +x 09_run_server_3
